### PR TITLE
Debugging coverage

### PR DESCRIPTION
**Pull request by stevepeak**
Do not merge. Debugging coverage

### CODE REVIEW

**Comment by stevepeak** [comment]
Looks like no Profdata file was found: https://travis-ci.org/SRandazzo/Verona/builds/84639047#L500

Is coverage enabled? https://github.com/codecov/example-swift

**Comment by SRandazzo** [comment]
@stevepeak Thanks for much for helping debug this!

I've found something quite interesting that might be worth noting -

The current version of XCTool (0.2.6), which Verona was using, does not support/honor generating the `Coverage.profdata`. 

I locally confirmed this by running my `test.sh` with xctool, which produced no Coverage.profdata.
I then switched to XCodeBuild, re-ran the test.sh, and bam! `Coverage.profdata`

I really appreciate your extra effort fixing this! Going to clean up my branch and get it merged :tada:

**Comment by SRandazzo** [comment]
Going to close as this is now working on https://github.com/SRandazzo/Verona/pull/5

Thank you again for all your help :rocket: ! Can't wait to integrate CodeCov on all my projects :+1:

**Comment by SRandazzo** [comment]
@stevepeak should have referenced this as well: https://github.com/facebook/xctool/issues/574
Just incase anyone else has this issue! Thanks again!

```
I was doing some digging when I noticed xctool also does not respect the /Scheme/TestAction/@codeCoverageEnabled setting in .xcscheme files. This is the equivalent of the -enableCodeCoverage YES option.
```

**Comment by stevepeak** [comment]
Thanks @SRandazzo I'll update the Readme to include this https://github.com/codecov/example-xcode

**Pull request closed without merging**
